### ISSUE TITLE
No longer applying balance in WC 2.3

### ISSUE THREAD

**Issue by ramiabraham** [ramiabraham/AffiliateWP-Store-Credit#5]
Doesn't seem to work with WC 2.3; @sumobi and I tested locally to confirm customer issue, and it reloads the page and doesn't apply the balance. The box is still present on the page.

**Comment by pmgarman** [comment]
Seems like `calculate_cart_subtotal` is not returning the actual cart total, causing everything to bomb out. Checking into this for a fix.

**Comment by ryanduff** [comment]
Awesome. Love breaking changes in WC.  :broken_heart:

Here's the related ticket on their side for reference in case this needs additional attention. Thanks for the fix. 

https://github.com/woothemes/woocommerce/issues/6873

https://github.com/woothemes/woocommerce/commit/1c696a10d3aa96edb31861888a9ce51889a7a885
